# Generated by Django 4.0.2 on 2022-02-12 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TpoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_ctc', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=100)),
                ('status', models.CharField(default='HIRING', max_length=10)),
                ('image', models.ImageField(default='default1.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('profile', 'Have a profile view')],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=25)),
                ('desc', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=20)),
                ('image', models.ImageField(default='default2.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('dashboard', 'Have a dashboard view'), ('create_post', 'Can create Job alerts')],
            },
        ),
    ]
