# Generated by Django 4.0.2 on 2022-02-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tpoprofile_companyprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tpoprofile',
            options={'permissions': [('profile', 'Have a profile view'), ('have_profile', 'Have a profile')]},
        ),
    ]
