# Generated by Django 4.0.2 on 2022-02-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_tpoprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tpoprofile',
            options={},
        ),
    ]
